import type { Contact, Job, WorkOrder, Note, Photo } from '@/lib/types';

const contacts: Contact[] = [
  { id: 'contact-1', name: 'Alice Johnson', phone: '555-0101', email: 'alice@example.com', address: '123 Main St, Springfield' },
  { id: 'contact-2', name: 'Bob Smith', phone: '555-0102', email: 'bob@example.com', address: '456 Oak Ave, Springfield' },
  { id: 'contact-3', name: 'Carol Williams', phone: '555-0103', email: 'carol@example.com', address: '789 Pine Rd, Springfield' },
  { id: 'contact-4', name: 'David Brown', phone: '555-0104', email: 'david@example.com', address: '321 Elm Blvd, Springfield' },
  { id: 'contact-5', name: 'Eva Martinez', phone: '555-0105', email: 'eva@example.com', address: '654 Maple Dr, Springfield' },
  { id: 'contact-6', name: 'Frank Davis', phone: '555-0106', email: 'frank@example.com', address: '987 Cedar Ln, Springfield' },
  { id: 'contact-7', name: 'Grace Wilson', phone: '555-0107', email: 'grace@example.com', address: '147 Birch Ct, Springfield' },
  { id: 'contact-8', name: 'Henry Anderson', phone: '555-0108', email: 'henry@example.com', address: '258 Spruce Way, Springfield' },
  { id: 'contact-9', name: 'Iris Thomas', phone: '555-0109', email: 'iris@example.com', address: '369 Willow Pl, Springfield' },
  { id: 'contact-10', name: 'Jack Taylor', phone: '555-0110', email: 'jack@example.com', address: '741 Aspen Cir, Springfield' },
  { id: 'contact-11', name: 'Karen Moore', phone: '555-0111', email: 'karen@example.com', address: '852 Poplar St, Springfield' },
  { id: 'contact-12', name: 'Leo Jackson', phone: '555-0112', email: 'leo@example.com', address: '963 Hickory Rd, Springfield' },
  { id: 'contact-13', name: 'Mia White', phone: '555-0113', email: 'mia@example.com', address: '159 Sycamore Ave, Springfield' },
  { id: 'contact-14', name: 'Noah Harris', phone: '555-0114', email: 'noah@example.com', address: '357 Magnolia Blvd, Springfield' },
  { id: 'contact-15', name: 'Olivia Clark', phone: '', email: 'olivia@example.com', address: '468 Redwood Dr, Springfield' },
  { id: 'contact-16', name: 'Paul Lewis', phone: '555-0116', email: 'paul@example.com', address: '579 Sequoia Ln, Springfield' },
];

const jobs: Job[] = [
  { id: 'job-1', contactId: 'contact-1', address: '123 Main St, Springfield', status: 'lead', value: 15000, title: 'Roof Replacement - Main St' },
  { id: 'job-2', contactId: 'contact-2', address: '456 Oak Ave, Springfield', status: 'scheduled', value: 22000, title: 'New Construction - Oak Ave' },
  { id: 'job-3', contactId: 'contact-3', address: '789 Pine Rd, Springfield', status: 'in_progress', value: 18000, title: 'Storm Damage Repair - Pine Rd' },
  { id: 'job-4', contactId: 'contact-4', address: '321 Elm Blvd, Springfield', status: 'lead', value: 25000, title: 'Commercial Roof - Elm Blvd' },
  { id: 'job-5', contactId: 'contact-5', address: '654 Maple Dr, Springfield', status: 'scheduled', value: 12000, title: 'Shingle Repair - Maple Dr' },
  { id: 'job-6', contactId: 'contact-6', address: '987 Cedar Ln, Springfield', status: 'in_progress', value: 30000, title: 'Full Replacement - Cedar Ln' },
  { id: 'job-7', contactId: 'contact-7', address: '147 Birch Ct, Springfield', status: 'lead', value: 8000, title: 'Leak Repair - Birch Ct' },
  { id: 'job-8', contactId: 'contact-8', address: '258 Spruce Way, Springfield', status: 'scheduled', value: 19000, title: 'Roof Inspection - Spruce Way' },
  { id: 'job-9', contactId: 'contact-9', address: '369 Willow Pl, Springfield', status: 'in_progress', value: 21000, title: 'Gutter Installation - Willow Pl' },
  { id: 'job-10', contactId: 'contact-10', address: '741 Aspen Cir, Springfield', status: 'lead', value: 16000, title: 'Skylight Flashing - Aspen Cir' },
];

const notes: Note[] = [
  { id: 'note-1', text: 'Left voicemail, retry after 3pm', timestamp: '2024-01-15T10:30:00-05:00' },
  { id: 'note-2', text: 'Confirmed appointment for Thursday', timestamp: '2024-01-14T14:20:00-05:00' },
  { id: 'note-3', text: 'Customer requested callback', timestamp: '2024-01-13T09:15:00-05:00' },
];

const workOrders: WorkOrder[] = [
  {
    id: 'wo-1',
    jobId: 'job-1',
    title: 'Tear-off rear section',
    assignee: 'Casey Rivera',
    scheduledDate: '2024-01-20',
    status: 'scheduled',
    notes: [],
    photos: [],
  },
  {
    id: 'wo-2',
    jobId: 'job-1',
    title: 'Install underlayment',
    assignee: 'Casey Rivera',
    scheduledDate: '2024-01-21',
    status: 'scheduled',
    notes: [],
    photos: [],
  },
  {
    id: 'wo-3',
    jobId: 'job-2',
    title: 'Framing inspection',
    assignee: 'Casey Rivera',
    scheduledDate: '2024-01-20',
    status: 'en_route',
    notes: [],
    photos: [],
  },
  {
    id: 'wo-4',
    jobId: 'job-2',
    title: 'Sheathing install',
    assignee: 'Alex Chen',
    scheduledDate: '2024-01-22',
    status: 'scheduled',
    notes: [],
    photos: [],
  },
  {
    id: 'wo-5',
    jobId: 'job-3',
    title: 'Remove damaged shingles',
    assignee: 'Casey Rivera',
    scheduledDate: '2024-01-18',
    status: 'on_site',
    notes: [{ id: 'note-4', text: 'Started tear-off at 8am', timestamp: '2024-01-18T08:00:00-05:00' }],
    photos: [],
  },
  {
    id: 'wo-6',
    jobId: 'job-3',
    title: 'Install new shingles',
    assignee: 'Jordan Kim',
    scheduledDate: '2024-01-19',
    status: 'scheduled',
    notes: [],
    photos: [],
  },
  {
    id: 'wo-7',
    jobId: 'job-4',
    title: 'Commercial membrane install',
    assignee: 'Casey Rivera',
    scheduledDate: '2024-01-25',
    status: 'scheduled',
    notes: [],
    photos: [],
  },
  {
    id: 'wo-8',
    jobId: 'job-5',
    title: 'Flashing repair',
    assignee: 'Casey Rivera',
    scheduledDate: '2024-01-20',
    status: 'done',
    notes: [],
    photos: [],
  },
  {
    id: 'wo-9',
    jobId: 'job-6',
    title: 'Complete tear-off',
    assignee: 'Casey Rivera',
    scheduledDate: '2024-01-19',
    status: 'blocked',
    notes: [],
    photos: [],
    blockedFromStatus: 'on_site',
    blockedReason: 'No roof access, gate locked, owner unreachable',
  },
  {
    id: 'wo-10',
    jobId: 'job-6',
    title: 'Deck inspection',
    assignee: 'Taylor Brooks',
    scheduledDate: '2024-01-23',
    status: 'scheduled',
    notes: [],
    photos: [],
  },
  {
    id: 'wo-11',
    jobId: 'job-7',
    title: 'Locate and seal leak',
    assignee: 'Casey Rivera',
    scheduledDate: '2024-01-20',
    status: 'on_site',
    notes: [],
    photos: [{ id: 'photo-1', uri: '/photos/leak-1.jpg', timestamp: '2024-01-20T09:00:00-05:00' }],
  },
  {
    id: 'wo-12',
    jobId: 'job-8',
    title: 'Full roof inspection',
    assignee: 'Morgan Lee',
    scheduledDate: '2024-01-22',
    status: 'scheduled',
    notes: [],
    photos: [],
  },
];

export const seedData = {
  contacts,
  jobs,
  workOrders,
  currentUser: 'Casey Rivera',
  crewMembers: ['Casey Rivera', 'Alex Chen', 'Jordan Kim', 'Taylor Brooks', 'Morgan Lee'],
};

export function getSeedData() {
  return seedData;
}