#!/bin/bash
# Prompt capture hook for AI-assisted development
# Usage: .kilo/hooks/capture-prompt.sh "tool:model" "verbatim prompt"
# This script appends to PROMPTS.md in the same commit as the work

set -e

TOOL_MODEL="${1:-unknown}"
PROMPT="${2:-}"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

if [ -z "$PROMPT" ]; then
  echo "Usage: $0 \"tool:model\" \"prompt text\""
  exit 1
fi

PROMPTS_FILE="PROMPTS.md"

# Create PROMPTS.md if it doesn't exist
if [ ! -f "$PROMPTS_FILE" ]; then
  cat > "$PROMPTS_FILE" << 'EOF'
# AI Prompt Log

This file is auto-generated by the prompt capture hook (`.kilo/hooks/capture-prompt.sh`).
Each entry records: timestamp, tool+model, and verbatim prompt.
Entries are committed alongside the work they produced.

EOF
fi

# Append the prompt entry
cat >> "$PROMPTS_FILE" << EOF

## $TIMESTAMP

**Tool/Model:** $TOOL_MODEL

**Prompt:**
\`\`\`
$PROMPT
\`\`\`

EOF

echo "Captured prompt to $PROMPTS_FILE"
EOF
chmod +x /Users/joelnieto/Projects/test-app/.kilo/hooks/capture-prompt.sh