#!/usr/bin/env node
/**
 * Prompt capture utility for AI-assisted development
 * Usage: node .kilo/hooks/capture-prompt.js "tool:model" "verbatim prompt"
 * Appends to PROMPTS.md with timestamp
 */

const fs = require('fs');
const path = require('path');

const [, , toolModel, ...promptParts] = process.argv;
const prompt = promptParts.join(' ');

if (!toolModel || !prompt) {
  console.error('Usage: node capture-prompt.js "tool:model" "prompt text"');
  process.exit(1);
}

const timestamp = new Date().toISOString();
const promptsFile = path.join(process.cwd(), 'PROMPTS.md');

let content = '';
if (!fs.existsSync(promptsFile)) {
  content = `# AI Prompt Log

This file is auto-generated by the prompt capture hook (\`.kilo/hooks/capture-prompt.js\`).
Each entry records: timestamp, tool+model, and verbatim prompt.
Entries are committed alongside the work they produced.

`;
}

content += `## ${timestamp}

**Tool/Model:** ${toolModel}

**Prompt:**
\`\`\`
${prompt}
\`\`\`

`;

fs.appendFileSync(promptsFile, content);
console.log(`Captured prompt to ${promptsFile}`);